- hosts: windows
  ansible_ssh_user: zep10031997@outlook.com
  ansible_ssh_password: 10Maret@1997
  ansible_ssh_port: 5985
  ansible_connection: winrm
  ansible_winrm_server_cert_validation: ignore
  
  

  tasks:
    - name: Ping Windows Hosts
      win_ping:
